{% set name = "fastscape" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fastscape-lem/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5aaafb3b1d7726b10f0d3809f6e21f9a90913d1f95f62b1d0c5a055830277d19

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3
    - xarray-simlab >=0.5.0
    - fastscapelib-f2py >=2.8.3
    - numba

test:
  imports:
    - fastscape

about:
  home: https://github.com/fastscape-lem/fastscape
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast, versatile and user-friendly landscape evolution models'
  doc_url: https://fastscape.readthedocs.io
  dev_url: https://github.com/fastscape-lem/fastscape

extra:
  recipe-maintainers:
    - benbovy
